### ISSUE TITLE
Accessing object with array notation

### ISSUE THREAD

**Issue by beatscode** [PetrSladek/Gcm#1]
On line 62 of petrsladek/gcm/src/Http/Response.php i would get error that i was trying to access an object with array notation. I added (array)Json::decode($body); Is there a reason why I'm getting this error? Is it because of my php version. It happened in environments with php 5.5.30 & php 5.4.37. 

![c8637f45-5760-4a89-ab8e-f29100553eae](https://cloud.githubusercontent.com/assets/1777648/11163660/aef8f5be-8aa5-11e5-99f5-1f9f1064e03c.png)

**Comment by PetrSladek** [comment]
Oh :(. Thak you for this issue. I fix it now on master branche.  :-)
Please test it.
