### ISSUE TITLE
Daemon->nMessage call back can't run

### ISSUE THREAD

**Issue by jackchanjw** [PetrSladek/Gcm#2]
$daemon->onReady[] = function(Daemon $daemon) {
    print "Ready / Auth success. Waiting for Messages";
};
$daemon->onAuthFailure[] = function(Daemon $daemon, $reason) {
    print "Auth failure (reason $reason)";
};
$daemon->onStop[] = function(Daemon $daemon) {
    print 'Daemon has stopped by $daemon->stop()';
};
$daemon->onDisconnect[] = function(Daemon $daemon) {
    print "Daemon has been disconected";
};
$daemon->onMessage[] = function(Daemon $daemon, \Gcm\RecievedMessage $message) {
    print "Recieved message from GCM";
    print_r($message);
};

Hi Sir,
  I have try to use your demo code and I can success get the onReady[] callback  and the prin" tReady / Auth success. Waiting for Messages" is okay.
  but After that, I can't receive the message for the CCS. 
  I use the android device to use the gcm send the upstream message to GCM server but the daemon can't receive the message? 
  Would you help me to solve it .
  Very Thanks
Jack Chan

**Comment by arkanmgerges** [comment]
Hi jackchanjw,

Today I had the same problem and I solved it, see the solution that I applied on this link:
[Xmpp daemon exits when it receives a message from gcm. (I fixed it)](https://github.com/PetrSladek/Gcm/issues/3)
